version: 0.2

phases:
  install:
    runtime-version:
      nodejs: latest 
    commands:
      - echo "installing packages"
  pre_build:
    commands:
      - echo "we are in the build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - grep -i "congratulations" index.html
  post_build:
    commands:
      - echo "we are in the post build phase"

